### ISSUE TITLE
Feature: Accept swagger files without `schemes` field

### ISSUE THREAD

**Issue by juhakivekas** [AresS31/swurg#10]
The `schemes` field in swagger is not mandatory, but swurg relies on it. Without the field swagger fails the file loading with a n Exception. The easy workaround for this is to add the field into the swagger file, but automatic guessing or user prompting could be a nice touch.

This issue is not very critical, but I'll make it visible by raising this issue.

**Comment by thomasstols** [comment]
The same goes for the "produces" field. Any entry without a "produces" field will result in a NullPointer Exception.

**Comment by AresS31** [comment]
@thomasstols I resolved the `scheme` issue, I will have a look at the produces issue as soon as I can.
Thanks for reporting the issue.

**Comment by hardikrana437** [comment]
@aress31 still we are getting error message : The OpenAPI specification contained in %s is missing the mandatory field: 'schemes'.
Is this a regression bug?

**Comment by aress31** [comment]
@hardikrana437 thanks for the comment, I suggest opening a ticket directly to https://github.com/PortSwigger/openapi-parser as I do not have the time to maintain this project at the minute.
