### ISSUE TITLE
[BUG] Gracefully Handle lack of "servers" object

### ISSUE THREAD

**Issue by AlLongley** [aress31/swurg#100]
# Prerequisites Checklist

Before submitting the issue, please make sure you have:

- [x] Thoroughly read the [README file](https://github.com/aress31/swurg/blob/main/README.md).
- [x] Checked the [project requirements](https://github.com/aress31/swurg#requirements) and ensured they are met.
- [x] Searched for existing issues that may address the problem.
- [x] Performed basic troubleshooting steps.

# Description

When loading in a Swagger generated OpenAPI JSON spec, there's no guarantee the "servers" object will be populated.

Loading a file of this type into the the OpenAPI parse Extension fails cryptically with

`Cannot invoke "io.swagger.v3.oas.models.media.Content.entrySet()" because the return value of "io.swagger.v3.oas.models.responses.ApiResponse.getContent()" is null`

similar [to this issue on the Burp Support forum](https://forum.portswigger.net/thread/openapi-parser-issue-when-importing-swagger-file-1fe83df8)

# Steps to Reproduce

1. Generate a JSON OpenAPI spec from Swagger
2. Check the "servers" root key is not-present (remove it if it is, to replicate bug)
3. Import JSON file directly, not via URL
4. Observe above error

# Expected Behavior

Hopefully a check for the presence of "servers" key and failing with a relevant error message should help the user rectify the fault manually. 
(Took me a few minutes of Googling to find https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#server-object-example)

Ideally in the absence of any "server" object, a prompt appears asking for the BaseURL of the server to test

**Comment by aress31** [comment]
If `server` is not present the extension now fallback to `example.com`.
