### ISSUE TITLE
[BUG] Can't build HTTP request for repeater and other burp tools

### ISSUE THREAD

**Issue by godfuzz3r** [aress31/swurg#101]
# Prerequisites Checklist

Before submitting the issue, please make sure you have:

- [x] Thoroughly read the [README file](https://github.com/aress31/swurg/blob/main/README.md).
- [x] Checked the [project requirements](https://github.com/aress31/swurg#requirements) and ensured they are met.
- [x] Searched for existing issues that may address the problem.
- [x] Performed basic troubleshooting steps.

# Description

Hi, I'm using examples from OpenAPI-Specification [json](https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v2.0/json) and [yaml](https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v2.0/yaml) examples (and json from projecton my job, which complies with the Swager 2.0 specification, but for obvious reasons I cannot show it) and none of them can't be represented as Burp suite request, just blank text. I tried enabling the use of http 1.0 only, but this doesn't help.

# Steps to Reproduce

1. load any of this examples: [json](https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v2.0/json) and [yaml](https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v2.0/yaml)
2. See that burp can't parse http, because there is a blank textm example on screenshot below.

# Expected Behavior

I should be able to send HTTP messages to another Burp tools such as Repeater or Intruder, but instead of a message, empty text is generated which cannot be recognized by Burp suite.

# Screenshots

![image](https://github.com/aress31/swurg/assets/24232540/cb38a84a-d649-43c5-b68b-320e46825956)

# Environment

- OS: Arch Linux x86_64 6.4.12-arch1-1
- Java version: openjdk 20.0.2 2023-07-18
- Gradle version: 8.1.1
- Burp Suite version: Professional 2023.10.1
- Swurg version: 4.0

# OpenAPI Specification
2.0 json and yaml

# Error Message

No error messages

**Comment by superbars** [comment]
Same problem

**Comment by err0rtic** [comment]
+++
same problem

**Comment by Techbrunch** [comment]
A temporary workaround is to change the HTTP protocol using the inspector once you have sent the request to the repeater and change it back. This appear to fixe the request.

**Comment by aress31** [comment]
86c1858ffe81eb0f1475cdcbdd161b10fb90f83b
