### ISSUE TITLE
[FEATURE] Send to Organizer

### ISSUE THREAD

**Issue by Techbrunch** [aress31/swurg#102]
It would be nice to add a "Send to Organizer" this would allow the user to easily send all the request to the Organizer and keep track of the requests that have been tested.

**Comment by aress31** [comment]
That's a good idea! @Techbrunch feel free to submit a PR, otherwise I will try to do that when I can.

**Comment by aress31** [comment]
86c1858ffe81eb0f1475cdcbdd161b10fb90f83b
