### ISSUE TITLE
"<<<<<<< HEAD" in the begginning of files

### ISSUE THREAD

**Issue by juhakivekas** [AresS31/swurg#2]
I'm failing to set this extension up and would love to edit the code, but it seems the files are some kind of diffs or have some metadata in them. 

Mostly I can see strings like `<<<<<<< HEAD`,  `=======`, and `>>>>>>> origin/master` that don't seem to be java code. The files affected are at least `DataStructure.java` and `ContextMenu.java`. If these are some residue from some tool or a mistake, then having them removed would enable me to debug and improve the extension.

**Comment by juhakivekas** [comment]
The following files in the repository are actually diffs between a `HEAD` and a `master ` branch. Just picking one or the other will let me edit the code. 

```
ContextMenu.java
DataStructure.java
Info.java
Parameter.java
Path.java
RESTful.java
Schema.java
Tab.java
```

**Comment by AresS31** [comment]
Good morning,

I am not very familiar with git as I mainly use it for hosting purpose.

I tried to reset the HEAD and to commit but it did not change anything.

Could you please tell me how to solve this issue?

Thanks,
Alex

**Comment by AresS31** [comment]
I tried to follow some tutorials on how to resolve Git conflicts with no luck.

I think I need to manually asses these files. I will do it as soon as I get free time.

Alex

**Comment by juhakivekas** [comment]
I actually fixed this. There are two versions that are in all the files, the other of which doesn't have the `Params` column. I'll do a PR in just a minute. Also, I dovument my work in these issues, dont feel at all obligated to fix everything at once :)

**Comment by juhakivekas** [comment]
I have both your `master` and `HEAD` separated in my fork as branches `fix_HEAD` and `fix_master`. I'm not sure which one is the newest version, but they both compile, and the `fix_HEAD` branch is the one that better corresponds to the `jar` file in the repository root (that version has the `Parameter` column)

**Comment by AresS31** [comment]
The `HEAD` branche is the latest one (containing the Params column). :)
