### ISSUE TITLE
Aborts when processing "post" or "put" stanzas

### ISSUE THREAD

**Issue by hlein** [AresS31/swurg#25]
I have a swagger 2.0 .json file that's got 172 different paths, 244 different path+method combinations.

Swagger Parser v1.4 from the Burp app store loads and imports the file without error, but only recognizes the first path, with three methods, for a total of three imported API calls.

I haven't started carving up my input file, or finished setting up a dev environment to play with the Swagger Parser code; thought I would ask if there's likely/known issues/limitations I should look for in particular.

**Comment by hlein** [comment]
Some progress: it seems to choke and stop loading at the first POST or PUT in the .json file.

Are PUT or POST methods tested / expected to work?  I notice that the screenshot shows only GETs.

I found the errors over in the Extender->Extensions->Swagger Parser->Errors pane :)

At the first "put" or "post" block, it will die with a stack trace like:

<pre>java.lang.NullPointerException
	at burp.Helper.parseSchemaParams(Helper.java:126)
	at burp.Helper.parseInBodyParams(Helper.java:109)
	at burp.Helper.populateHttpRequests(Helper.java:176)
	at burp.Tab.populateJTable(Tab.java:268)
	at burp.Tab.processFile(Tab.java:139)
	at burp.Tab.access$000(Tab.java:54)
	at burp.Tab$ButtonListener.actionPerformed(Tab.java:104)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
[snip]</pre>

For a POST, there is a "parameters" section like:

<pre>  "parameters": [
    {     
      "name": "data",
      "in": "body",
      "schema": {
        "type": "object",
        "title": "DoAThing",
        "properties": {
          "Paramone": {
            "type": "string",
            "example": "Somestring"
          },    
          "Paramtwo": {
            "type": "string"
          },    
        ...
      ...
    }
  ],
</pre>

The properties{} block inside schema{} doesn't seem substantially different from the properties{} blocks in GETs and DELETEs that do parse successfully.

If I remove the parameters{} block entirely, or change "in" from "body" to "query", Swagger Parser successfully gets past that entry in the .json (although of course Burp will then not do the right thing in testing).

PUTs typically have two parameters blocks, one '"in": "path"' which is fine, and one '"in":"body"' which has the same problem as the above for POSTs.

Just doing <code>s/"in": "body"/"in": "query"/g</code> causes the file to load, but then of course Burp won't actually do the right thing when trying to probe them.

I found where in <code>burp/Helper.java</code>, <code>parseInBodyParams</code> calls <code>parseSchemaParams</code>, and it's apparently dying at:
<pre>  for (Map.Entry<String, JsonElement> entry: definitions.entrySet()) {</pre>

I am a Java noob but just searching github that appears to be a common idiom, I don't see why it would be dying there.

I'm still testing with the extension version from the Burp App Store, can switch to a fresh build, gson 2.8.1, etc if that is likely to make a difference.

Thanks!

**Comment by AresS31** [comment]
@hlein sorry for the late reply, I have been really busy lately.

If you could send me the Swagger file generating this behavior via email, that would help me replicating and troubleshooting the issue.

Thanks,
Alex

**Comment by AresS31** [comment]
This issue might have been fixed with the latest release of `swurg`, please use the latest version of the plugin from this repository and let me know if you are still encountering issues with the specific Swagger file you were trying to parse.
