### ISSUE TITLE
The service's port is filtered from the Host parameter

### ISSUE THREAD

**Issue by chamaillard** [AresS31/swurg#28]
The host parameter from swagger.json is filtered and doesn't retrieve the service's port which won't be parameterized when sending a request to the repeater.

**Comment by AresS31** [comment]
Please provide an example of a Swagger file that would cause this issue. The default behavior of Swurg is to extract the host and ignoring the service port if there is any (e.g. www.example.com:80 would result in www.example.com for the host field). And a popup is prompted asking for the service protocol - the supported protocol are only HTTP and HTTPS at the moment - when the swagger file does not contain a scheme field.

**Comment by chamaillard** [comment]
Yes that's exactly what happens, when the port isn't 80, then the user need to edit the configuration in the repeater to adjust the port of the TCP connection:
That filtering seems to be superfluous since most of web servers accept port definition in Host header.

Example:
{
    "swagger": "2.0",
    "info": {
        "description": "XXX",
        "version": "XXX",
        "title": "XXXX",
        "contact": {},
        "license": {}
    },
    "host": "192.168.0.2:8080",
    "basePath": "/",
    "tags": [{
        "name": "....",
        "description": "XXXX"
    }, 
...

**Comment by AresS31** [comment]
The next release of `swurg` will solve this issue. You will be able to directly specify the port to use in the `host` field of the Swagger spec as follows:
<host>:<port>
