### ISSUE TITLE
Suggested feature - recent history of parsed resources

### ISSUE THREAD

**Issue by bao7uo** [aress31/swurg#41]
Suggested feature - recent history of parsed resources

Make the text box a combobox, and each time a new file/URL is opened add it to the combobox's list to record a history of previous files URLs. These could then be saved in the persistent configuration provided by Burp's API. Also, a button to "clear history" to remove the saved files/URLs.

When you send a request to swagger it could also add that as a URL to the history list, perhaps even place it in the text box at the top.

**Comment by AresS31** [comment]
That is a good idea, added to to do list. If you fancy implementing it, go ahead. :)

**Comment by aress31** [comment]
https://github.com/aress31/swurg/commit/b17952f8e68e3b661f6e835f062860083a68df90
