### ISSUE TITLE
base path not being appended to urls when sending to other Burp tools?

### ISSUE THREAD

**Issue by k4otix** [AresS31/swurg#47]
Not sure if this is an extension issue or something wrong with our swagger.json. The table in the Swagger Parser tab looks correct (host, base path, endpoint, params are all populated). But when I send these to the site map they are all added under the root directory of the host without the base path being included. Same with sending to intruder/repeater - the requests are to "/endpoint" on the host, not to "/my_api/v1/endpoint".

Any pointers/possible issues?

**Comment by AresS31** [comment]
@k4otix  thanks for the the feedback I will try to have a look at it this week if I got free time. The plugin underwent a massive code refactor. This might have introduced this bug.

**Comment by AresS31** [comment]
Issue fixed!

Compile the version present in this repository and import the jar file into Burp.

I just issued a pull request to the PortSwigger fork; therefore, it might take some time before they update the version present on the BApp store.
