### ISSUE TITLE
Wrong request sent to the repeater when a different sorting is used

### ISSUE THREAD

**Issue by eur0pa** [AresS31/swurg#55]
Hi there.
When sorting the Parser table with a different key (ie, sorting by Method), the wrong request will be sent to the Repeater tab. I assume the original, default sorted one gets sent, instead of the one currently highlighted.

**Comment by AresS31** [comment]
Hi @eur0pa 

Thanks for reporting the bug. I will work on the issue when I can.

Regards
Alex

**Comment by AresS31** [comment]
#51
