### ISSUE TITLE
Doesn't work on some samples

### ISSUE THREAD

**Issue by simonuvarov** [AresS31/swurg#56]
Hi,

I tried to import my swagger file and it didn't work. Then I tried to use some samples from GitHub.

It didn't work on this sample: 
https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/api-with-examples.yaml

But it did on this one:
https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore-minimal.yaml

Do I miss something? Or maybe you know how I can fix it?

**Comment by AresS31** [comment]
Hi @simonuvarov 

The explanation is simple, OpenAPI Parser expects to receive a properly formed OpenAPI document. In the specification contained at https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/api-with-examples.yaml you can see the `host` and `schemes` field are missing, these fields are mandatory.

Kind regards
Alex

**Comment by einfallstoll** [comment]
Hi Alex,

I believe you're wrong. The only top-level properties that are required according to the [JSON Schema for Swagger 2.0 API](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json) are:
- swagger
- info
- paths

As for the [OpenAPI Specification 3.0.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schema) the only required top-level fields are:
- openapi
- info
- paths

Also the "host" and "schemes" fields in 3.0.2 are not even supported anymore.

So "the explanation is simple", in either way your parser is too strict or wrong.

Regards, Fabio

**Comment by Gby56** [comment]
Hi !
I thought this was fixed in https://github.com/AresS31/swurg/issues/10 but I encountered the same issue, could this be a regression bug ?
