### ISSUE TITLE
Adding example params and resolve DTOs

### ISSUE THREAD

**Issue by monoxacc** [aress31/swurg#59]
Hi, 
Swagger Code-Gen has an [example generator](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/examples/ExampleGenerator.java)

You can use this to **automatically resolve DTOs and generate example bodys** for requests.
Simply copy ExampeGenerator.java and use it in your /src/main/java/swurg/utils/ExtensionHelper.java
Example usage:
`ExampleGenerator gen = new ExampleGenerator(swagger.getDefinitions());`
`List<Map<String,String>> generatedList = gen.generate(null, expectedTypes, refmodel.getSimpleRef());`

I already implemented this in an older version of your extension. Here a part of my implementation as gist as detailed usage example: https://gist.github.com/monoxacc/130818c3dbe1fe360bef12eba5c74ace

**Comment by aress31** [comment]
Sorry for the late reply, awesome job and addition to Swurg!
