### ISSUE TITLE
Additional fields option

### ISSUE THREAD

**Issue by digininja** [aress31/swurg#62]
It would be really good to have some way to automatically add extra headers as the request is being sent to repeater etc. I'm currently having to manually add the `Authorization: Bearer` after each request has been sent.

**Comment by aress31** [comment]
You can use the Burp Suite built-in features to achieve what you described, see under 'Proxy -> Options'. Or alternatively, you can use the CPH extension or similar extensions to add/change/tamper with HTTP headers. There are plenty of options out there and therefore it is not a priority to add additional fields to Swurg but if you would like to volunteer a PR would be more than welcome. :)

**Comment by digininja** [comment]
Off the top of my head, proxy options doesn't affect things being sent from
repeater so that wouldn't work.

I've not tried any other plugins to see if there is one that would modify
every request going out of Burp regardless of where it originated.

**Comment by aress31** [comment]
Take a look at the CPH extension, this is what you want to use.

**Comment by digininja** [comment]
Will do.
