### ISSUE TITLE
The OpenAPI specification obtained in XXXX is ill formed and cannot be parsed

### ISSUE THREAD

**Issue by vincentcox** [AresS31/swurg#64]
In SwaggerHub I try to export the YAML or JSON file like this:

![image](https://user-images.githubusercontent.com/9286611/60887666-31a00000-a255-11e9-9617-bc1542f8145c.png)

When I try to import the file in burp I get the error **"The OpenAPI specification obtained in XXXX is ill formed and cannot be parsed"**.

I tried to validate the YAML (or JSON) file with the swagger-cli validate command:

![image](https://user-images.githubusercontent.com/9286611/60887471-d3731d00-a254-11e9-8d96-17852d62099a.png)

It seems that the file is correct. 

Unfortunately I cannot share the YAML or JSON files.

Any ideas what I can check or try on my side?

**Comment by MacJu** [comment]
It seems that the version 3 format of OpenAPI files don't get parsed well yet.
A current workaround is to convert the file to version 2 format.
www.apimatic.io does a great job converting the files.

**Comment by vincentcox** [comment]
Thanks Mac! ❤️ That did the trick.
