### ISSUE TITLE
More verbose errors

### ISSUE THREAD

**Issue by vaadataa** [aress31/swurg#65]
Hi,

Is there a way to get access to more verbose errors ?

I would love to use this plugin but for some reason my file can't be parsed, I'm getting the error:

```
The OpenAPI specification contained in %s is ill formed and cannot be parsed
```

I see that the Swagger Parser is quite old, maybe updating it would solve the issue.

**Comment by lanmaster53** [comment]
Same here. I've not been able to parse an OpenAPI file with this extension for a very long time. Is this project still being maintained?

**Comment by aress31** [comment]
@lanmaster53 due to other commitment I do not have the time right now to maintain this project, any PR are appreciated and/or alternatively you could open a ticket at https://github.com/PortSwigger/openapi-parser so that the guys at PortSwigger implement the requested changes.
