### ISSUE TITLE
Unable to parse/load OpenAPI 3 YAML or JSON

### ISSUE THREAD

**Issue by davidroberts63** [aress31/swurg#67]
When trying to parse/load the YAML or JSON from the Swagger Pets store example (linked below), The parser responds at the bottom with 'The OpenAPI specification contained in c:\source\pets3.yml is ill formed and cannot be parsed.

Is there any way to get more details on the problem it's having with the file? Same response for JSON.

When parsing the 2.0 version though everything works as expected.

We are using the Pet store example available in the [Swagger Editor](https://swagger.io/tools/swagger-editor/). The exact files are attached as well.

Yaml format
[pets3.txt](https://github.com/aress31/swurg/files/4561215/pets3.txt)

**Comment by podjackel** [comment]
For a sanity check, I ran `pets3.txt`  through the [swagger-cli](https://github.com/APIDevTools/swagger-cli) and it is valid, but fails to parse in either YAML or JSON format.

![pets3 validation](https://user-images.githubusercontent.com/5067183/86257586-5c2e4b80-bb7f-11ea-9526-4b4fcae48f0b.png)

**Comment by hardikrana437** [comment]
@aress31 can you comment on this?  I think the support for OpenAPI 3 is still not there. This is long due feature I guess for many of us.

**Comment by aress31** [comment]
Related to #68

**Comment by aress31** [comment]
@hardikrana437 & @davidroberts63 `Swurg` now supports `OAS 3.0`! 🥳 Grab the latest version and let me know if you spot any bugs.
