### ISSUE TITLE
Changes to swagger-parser for OAS3.0 Support

### ISSUE THREAD

**Issue by aph3rson** [aress31/swurg#68]
Hi there,

I've been trying to use swurg with an OAS 3.0 API document. It fails the import process, stating that the document is ill formed.

After reviewing the swurg code, it appears that swurg is still configured to use the V2-compatible version of the parser: https://github.com/aress31/swurg/blob/f592a287d3f588ddd01f895925584546c246b050/src/main/java/swurg/process/Loader.java#L47

Per their [README](https://github.com/swagger-api/swagger-parser/blob/master/README.md), swagger-parser has a new syntax for parsing V3 files:  
```
import io.swagger.v3.parser.OpenAPIV3Parser;
import io.swagger.v3.oas.models.OpenAPI;

// ... your code

// read a swagger description from the petstore
  
  
  OpenAPI openAPI = new OpenAPIV3Parser().read("https://petstore3.swagger.io/api/v3/openapi.json");
```

It looks like this would need to be called rather than the old SwaggerParser constructor for full V3 support. Additionally, an option should be added to the UI to parse as V2 or as V3, depending on the file (or detect it automatically).

**Comment by aress31** [comment]
Hi @aph3rson thanks for opening this ticket, I do not really have the time to maintain this project at the minute, so feel free to open a ticket at https://github.com/PortSwigger/openapi-parser, or to alternatively submit a PR.

**Comment by aress31** [comment]
@aph3rson please see the latest released version, I addressed this issue and `Swurg` now supports all version of OAS up to `3.x`. 🥂
