### ISSUE TITLE
InteliJ-specific files tracked in repo

### ISSUE THREAD

**Issue by aph3rson** [aress31/swurg#69]
There's a number of InteliJ-specific files in the .idea folder which are specific to the maintainer's environment. A proper gitignore for JetBrains IDEs should be tracked ([GitHub has a great example of one](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore)), and the unnecessary files removed.

This is an easy win, and could be bundled in with another PR.

**Comment by aress31** [comment]
@aph3rson, feel free to submit the relevant PR :)
