### ISSUE TITLE
Missing mandatory field: 'host'

### ISSUE THREAD

**Issue by Techbrunch** [aress31/swurg#71]
I ran into this issue a couple of time:

```
The OpenAPI specification contained in https://.../api/v2/swagger/json is missing the mandatory field: 'host'
```

Adding the host in the JSON fixed the issue:

```json
{
    "basePath": "/api/v2",
    "host": "www.xxx.com",
    "definitions": {
```

I would be nice to default the host to the host of the swagger doc when it's not set and we pass a URL to OpenAPI Parser.

**Comment by ReverseBrain** [comment]
I totally agree with this solution, I solved the same problem adding the host in the JSON.
