### ISSUE TITLE
Can we send the requests  to sitemap automatically?

### ISSUE THREAD

**Issue by hardikrana437** [aress31/swurg#72]
I have my burp running at 8080 port.

I want to send the requests for scan through automation.

Is that possible?

**Comment by hardikrana437** [comment]
@bao7uo @aress31 any idea?

**Comment by aress31** [comment]
Hi @hardikrana437 you will have to feed `Swurg` with the `Open API` specification, you can either upload the file or just enter the URL where this specification is hosted. You have to make sure that it is either in `YAML` or `JSON` format.

I am now closing this ticket, if any issue feel free to follow up.

**Comment by hardikrana437** [comment]
@aress31 So this can be done through UI only or through code also we can load the extension and then add it to sitemap?
