### ISSUE TITLE
Bypass SSL error certificate

### ISSUE THREAD

**Issue by ulises2k** [aress31/swurg#85]
Hello, is it possible to avoid the use of the tool due to an error in the certificate?
It usually happens when the certificate was created for a domain and is entered by IP. I don't know what the domain is, I only know the IP. The plugin gives me the following error:
![image](https://user-images.githubusercontent.com/2415609/176954288-46d65a9e-a9c7-4c92-bd24-b3f0e496280c.png)

**Comment by aress31** [comment]
An easy fix would be to locally copy the content of the file and load it as a file rather than URL.

**Comment by ulises2k** [comment]
I do Pentesting/Vulnerability Assessment, I only have access to the URL.
90% of people who use burpsuite do the same (Vulnerability Assessment/Pentest)

**Comment by aress31** [comment]
As a pentester you should know that if you have access to the URL then you have access to the response body. I recommend you look up the `curl` or `wget` doc...

**Comment by ulises2k** [comment]
Sorry, could you modify the plugin so it can be used even if the certificate is invalid?

**Comment by aress31** [comment]
I don't really want to allow fetching through insecure SSL connections as default behaviour,  therefore work need to be done to add a tick box to enable this option. Will add this feature in the backlog in the meantime as suggested locally download the response (OpenAPI spec) and just load it as a file. You can do that through `curl`, `wget` or a simple copy, paste into notepad.

**Comment by ulises2k** [comment]
It should allow me to use it if the SSL certificate is not correct, it could be signed by myself, or I do not have the correct CA but if the correct website works, the plugin should work.
