### ISSUE TITLE
OpenAPI parser doesn't load the swagger file in YAML format

### ISSUE THREAD

**Issue by MMquant** [aress31/swurg#86]
Burp Suite version v2021.12.1
The latest Swurg version installed from the Github repository.
![image](https://user-images.githubusercontent.com/20891620/177108015-92341cbe-46a9-472d-bb65-a99ba8228478.png)
Testing YAML OpenAPI definition at [https://brp.mmquant.net/943b9a26-fb6c-11ec-b939-0242ac120002.yaml](https://brp.mmquant.net/943b9a26-fb6c-11ec-b939-0242ac120002.yaml)
Error message in the Burp Extender tab
![image](https://user-images.githubusercontent.com/20891620/177108519-79191da0-d157-42ca-98f8-087ec6aae1cb.png)

**Comment by aress31** [comment]
https://github.com/aress31/swurg/commit/044ac747e10d5e19d18f50a00583bc16b37440e1
