### ISSUE TITLE
Parsing errors on various openapi specs

### ISSUE THREAD

**Issue by Gby56** [aress31/swurg#87]
Hi !

I'd like to help out on the project, but I don't really remember how to debug the code anymore, and the logs are not super verbose to explain "where in the spec" it failed

Here are a few examples:
`https://bugcrowd.com/openapi/2021-10-28/openapi.yml`

```
Cannot invoke "java.util.Map.entrySet()" because "properties" is null
```

`https://www.secureflag.com/management/api/swagger-config.yaml`

```
attribute is not of type `object`
```

`https://app.swaggerhub.com/apiproxy/schema/file/apis/Veracode/veracode-sca_agent_api_specification/3.0?format=json`

```
attribute paths. '/v3/workspaces/{id}/issues'(get).[status].default is not of type `array`]
```

I'm mostly interested in using swurg to understand how I could automatically download data from APIs, not really testing them, but this is already showing me how hard it is to parse and use OpenAPI specs... 😅 
I'd be curious to see if swurg could have a "fail-safe" mode that just tries the list APIs that don't need any input parameter ? that would make the import more robust ?

**Comment by aress31** [comment]
Upgraded the project to `Burp Montoya` and decoupled UI to logic to the best of my knowledge. Now it should be much easier to troubleshot. Any PR would be appreciated! 😀
