### ISSUE TITLE
Cannot invoke "io.swagger.v3.oas.models.OpenAPI.getServers()" because "openAPI" is null

### ISSUE THREAD

**Issue by rm1984** [aress31/swurg#88]
Hi, I'm encountering the following problem  while trying to load a YAML swagger file (OpenAPI 3.0.1) from local disk.
Running BurpSuite Professional 2022.3.8.
Using OpenAPI Parser 3.0a from PortSwigger [BApp Store](https://portswigger.net/bappstore/6bf7574b632847faaaa4eb5e42f1757c).

![burp](https://user-images.githubusercontent.com/10762991/186885055-49fddde3-f2e2-47de-b33e-958ce06ca908.png)

Thanks!

**Comment by cyc10n3** [comment]
@rm1984 try to compile the code from the repo and load the jar file instead. It worked for me.

**Comment by aress31** [comment]
https://github.com/aress31/swurg/commit/044ac747e10d5e19d18f50a00583bc16b37440e1
