### ISSUE TITLE
Context menu not working on OSX and Debian

### ISSUE THREAD

**Issue by juhakivekas** [AresS31/swurg#9]
The windows version of the extension works fine, but on other paltforms the context menu does not appear. I'm running java versions `1.8.0_101` and `1.8.0_77` on OSX ElCapitan and Debian 8 without success and `1.8.0_111` on Windows with success.

**Comment by thomasstols** [comment]
Great extension, however currently unusable on MacOS since the context menu doesn't work.
Could you have a look at MacOS support?

**Comment by AresS31** [comment]
@thomasstols, I do not have an Apple system. So unfortunately, I will not be able to torubleshot this issue.

**Comment by giooootis** [comment]
Just an FYI since you are mentioning Linux as an alternative, context menu is not working on Debian 8 too.

**Comment by doomguy** [comment]
Running BurpPro v1.7.21 (latest as of today) on Kali Rolling doesn't seem to work either. I can load a test.json I grabbed from "http://editor.swagger.io/" (api.uber.com) but if I do a right click or double click on any of the entries, nothing happens. 

Any suggestions?

Thanks for your feedback.

**Comment by AresS31** [comment]
I reported the issue to PortSwigger, hopefully they look into the issue and get back with a fix. I spent time researching the issue myself and there is absolutely no reason (as far as I know) for the ContextMenu not to work since Java is platform independant if working under Windows it should work under Mac and Linux.

**Comment by robertofpaf** [comment]
Having the same problem here with Debian: the swagger file gets parsed properly but I cannot do anything with it as neither clicking nor right-clicking triggers any action.
