### ISSUE TITLE
Issue when loading a swagger

### ISSUE THREAD

**Issue by KernowSec** [aress31/swurg#90]
When trying to load an openapi v3 swagger, i get this error:

`swurg.gui.ParserPanel$LoadButtonListener -> Cannot invoke "io.swagger.v3.oas.models.media.Content.entrySet()" because the return value of "io.swagger.v3.oas.models.responses.ApiResponse.getContent()" is null`

**Comment by gl4nce** [comment]
Same here. Plugin is broken?
