### ISSUE TITLE
Support for JSON body types

### ISSUE THREAD

**Issue by martinknafve** [aress31/swurg#91]
I wonder if body:s with JSON content-type are supported?

I've imported an OpenAPI file where requestBody content is `application/json`, but the content type in the imported entry is instead `application/x-www-form-urlencoded`. When I import the same file in other software (such as Postman and SwaggerUI) the body content type is handled properly.

I am not familar with the source code of this extension, but in ExtensionHelper.convertContentTypeToBurpCode it looks like it's just not implemented, but mostly wanted to double-check if I have missed something. One of the mentioned features is "fully compliant with OpenAPI 2.0/3.0 Specifications", but as I understand it only specific parts of the OpenAPI specification is implemented.

**Comment by aress31** [comment]
Now `JSON` parameters _should in theory_ be supported with my port to the `Montoya API`. Please compile and test the latest version of the plugin and let me know if it fixed your problem.
