### ISSUE TITLE
parseAccept throws null pointer exception when content is not set

### ISSUE THREAD

**Issue by process0** [aress31/swurg#92]
The `ExtensionHelper.parseAccept` method throws a null pointer exception when the content is not set in the openAPI spec.  

This may be related to issues:
* https://github.com/aress31/swurg/issues/76
* https://github.com/aress31/swurg/issues/74
* https://github.com/aress31/swurg/issues/90
* https://github.com/aress31/swurg/issues/87

And is hinted at in the comment https://github.com/aress31/swurg/issues/74#issuecomment-1088747957

Adjusting the affected lines allows for the spec to be parsed properly:

```java
    if (responses != null && responses.get("200") != null && responses.get("200").getContent() != null) {
      for (Map.Entry<String, MediaType> response : responses.get("200").getContent().entrySet()) {
        stringJoiner.add(response.getKey());
      }
    }
```

Debugging this was made harder due to the try/catch and the error message output, in this case `Class name -> null`. Removing these and allowing the exception to dump the stack trace made the error immediately apparent.  

I suggest this is done in all places where exceptions are not to be expected or to include a stack trace in those instances.

**Comment by aress31** [comment]
@process0 do you mind opening a PR for this?
